@baseUrl = http://localhost:7071
#@baseUrl = https://<your-app>.azurewebsites.net

@code =
@taskHub = azcapacity
@connection = AzureDurableFunctionStorage


### Refresh the unique VM SKU catalog across all regions
POST {{baseUrl}}/api/data-collection/compute_skus/refresh?code={{code}}
Content-Type: application/json

{}


### Status
GET {{baseUrl}}/api/data-collection/compute_skus/status?code={{code}}


### Flush the catalog and checkpoint tables
POST {{baseUrl}}/api/data-collection/compute_skus/flush?code={{code}}
Content-Type: application/json

{}


### Check orchestration status
@instanceId = 00000000000000000000000000000000
GET {{baseUrl}}/runtime/webhooks/durabletask/instances/{{instanceId}}?taskHub={{taskHub}}&connection={{connection}}&code={{code}}